* Todo [0/2]
  - [ ] Would be nice to (optionally) include tags in `--vals` listing
    Maybe length of value displayed as well?
  - [ ] Would be nice to be able to sort by date
    This is implicit in `-b` (sort by newest first), but being explicit would be better.


* Bugs [0/3]
  - [ ] When piping multiple values to `pbcopy` only the last one
  - [ ] When command in config.yaml has space (eg `ls -la`) the command will fail
    Because "ls -la" is not a command.
    Need to split on spaces, use the first as command, rest as args.
  - [ ] Error when changing permissions of backup file


* Improvements / optimizations [1/4]
  - [ ] Pass pointers of other long-passed parameters?
    As with the user's Config.
  - [ ] Allow user to pipe to arbitrary tools via command line option?
  - [ ] Error messages from shell commands?
    Currently "Error running `/usr/bin/open wicked game`: exit status 1" instead of "The file /Users/richardmavis/Code/go/src/gitlab.com/u/rmavis/gostar/wicked does not exist."
  - [X] Better message in prompt
    Include the command name, etc
