* Todo [3/5]
  Always: grep -i "todo" *.go
  - [X] Create records
  - [X] Delete records
  - [X] Wrapup function
    After acting on value.
    Update touched date and count, etc.
  - [ ] Edit records
    Open in editor, etc.
  - [ ] Improved documentation



* Bugs [1/4]
  - [X] When writing to backup file, only wanted records are part of `records`!!!!!
  - [ ] Error when changing permissions of backup file
  - [ ] When piping multiple values to `pbcopy` only the last one
  - [ ] When command in config.yaml has space (eg `ls -la`) the command will fail
    Because "ls -la" is not a command.
    Need to split on spaces, use the first as command, rest as args.



* New features [1/2]
  - [X] Browse! Sheesh.
  - [ ] Allow user to pipe to arbitrary tools
    Via command line option or config.yaml



* Would be nice / optimizations [1/3]
  - [ ] Pass pointers to `conf` instead of copies
  - [ ] Error messages from shell commands?
    Currently "Error running `/usr/bin/open wicked game`: exit status 1" instead of "The file /Users/richardmavis/Code/go/src/gitlab.com/u/rmavis/gostar/wicked does not exist."
  - [X] Better message in prompt
    Include the command name, etc
